### ISSUE TITLE
Tabs!

### ISSUE THREAD

**Issue by prichey** [40Digits/polaris#3]
There are still lots of files using tabs for indentation rather than spaces.

**Comment by ckhicks** [comment]
Definitely a good thing to check as we roll through and run cleanup here.

**Comment by prichey** [comment]
Resolved by https://github.com/40Digits/polaris/pull/4.

**Comment by prichey** [comment]
Opening because the PR I referenced earlier was just to `development` branch. Will close after merging with master.

**Comment by prichey** [comment]
Resolved by https://github.com/40Digits/polaris/commit/86f9bae0137db259a35930d68f12db717ef7fac2.
